language: python
dist: xenial
install:
  - pip install -q -r requirements.txt
  - pip install coveralls
matrix:
  include:
    - python: 3.7
      env: DJANGO_VERSION='Django>=2.2,<3.0'
  fast_finish: true
script:
  coverage run --source=protector setup.py test
after_success:
  coveralls
